### ISSUE TITLE
Handle bad responses

### ISSUE THREAD

**Issue by maximusunc** [TranslatorSRI/PerformanceTestRunner#3]
It looks like a service sent something back incorrectly? Here's the logs:
```text
[2024-05-20 14:53:45,398: ERROR/root]: Error in getting futures back
[2024-05-20 14:53:45,413: ERROR/root]: Unexpected error 4: ['Traceback (most recent call last):\n', '  File "/Users/mwang/CoVar/translator/sri/testing/PerformanceTestRunner/PerformanceTestRunner/load_test.py", line 402, in stress_individual_agents\n    json_data= json.loads(stringv)\n', '  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads\n    return _default_decoder.decode(s)\n', '  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n', '  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode\n    raise JSONDecodeError("Expecting value", s, err.value) from None\n', 'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n']
[2024-05-20 14:53:45,413: ERROR/root]: <traceback object at 0x105b04d80>
```

**Comment by maximusunc** [comment]
This also caused the rest of the services in the list to not get evaluated

**Comment by ShervinAbd92** [comment]
changed to asyncio to handle these tasks in the updated code release
